In [2]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
lung_cancer = "Resources/survey_lung_cancer_rawdata.csv"


# Read the  Data and  store into a Pandas DataFrame
lung_cancer_df = pd.read_csv(lung_cancer)

lung_cancer_df.tail(10)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
299,M,65,YES,YES,YES,YES,NO,YES,YES,NO,NO,NO,YES,YES,NO,YES
300,F,63,YES,YES,YES,YES,YES,YES,YES,YES,NO,YES,YES,YES,YES,YES
301,M,64,NO,YES,YES,YES,NO,NO,YES,NO,YES,NO,NO,YES,YES,YES
302,F,65,YES,YES,YES,YES,NO,YES,NO,YES,NO,YES,YES,YES,NO,YES
303,M,51,NO,YES,NO,NO,YES,YES,YES,YES,YES,YES,YES,NO,YES,YES
304,F,56,NO,NO,NO,YES,YES,YES,NO,NO,YES,YES,YES,YES,NO,YES
305,M,70,YES,NO,NO,NO,NO,YES,YES,YES,YES,YES,YES,NO,YES,YES
306,M,58,YES,NO,NO,NO,NO,NO,YES,YES,YES,YES,NO,NO,YES,YES
307,M,67,YES,NO,YES,NO,NO,YES,YES,NO,YES,YES,YES,NO,YES,YES
308,M,62,NO,NO,NO,YES,NO,YES,YES,YES,YES,NO,NO,YES,NO,YES

In [3]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
lung_cancer = "Resources/survey lung cancer.csv"


# Read the  Data and  store into a Pandas DataFrame
lung_cancer_df = pd.read_csv(lung_cancer)

lung_cancer_df.tail(10)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
299,M,65,2,2,2,2,1,2,2,1,1,1,2,2,1,YES
300,F,63,2,2,2,2,2,2,2,2,1,2,2,2,2,YES
301,M,64,1,2,2,2,1,1,2,1,2,1,1,2,2,YES
302,F,65,2,2,2,2,1,2,1,2,1,2,2,2,1,YES
303,M,51,1,2,1,1,2,2,2,2,2,2,2,1,2,YES
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [4]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
total_cancer_death = "Resources/total-cancer-deaths-by-type.csv"


# Read the  Data and  store into a Pandas DataFrame
total_cancer_death_df = pd.read_csv(total_cancer_death)

total_cancer_death_df.tail(10)

,Entity,Code,Year,Deaths - Liver cancer - Sex: Both - Age: All Ages (Number),Deaths - Kidney cancer - Sex: Both - Age: All Ages (Number),Deaths - Lip and oral cavity cancer - Sex: Both - Age: All Ages (Number),"Deaths - Tracheal, bronchus, and lung cancer - Sex: Both - Age: All Ages (Number)",Deaths - Larynx cancer - Sex: Both - Age: All Ages (Number),Deaths - Gallbladder and biliary tract cancer - Sex: Both - Age: All Ages (Number),Deaths - Malignant skin melanoma - Sex: Both - Age: All Ages (Number),...,Deaths - Brain and central nervous system cancer - Sex: Both - Age: All Ages (Number),Deaths - Non-Hodgkin lymphoma - Sex: Both - Age: All Ages (Number),Deaths - Pancreatic cancer - Sex: Both - Age: All Ages (Number),Deaths - Esophageal cancer - Sex: Both - Age: All Ages (Number),Deaths - Testicular cancer - Sex: Both - Age: All Ages (Number),Deaths - Nasopharynx cancer - Sex: Both - Age: All Ages (Number),Deaths - Other pharynx cancer - Sex: Both - Age: All Ages (Number),Deaths - Colon and rectum cancer - Sex: Both - Age: All Ages (Number),Deaths - Non-melanoma skin cancer - Sex: Both - Age: All Ages (Number),Deaths - Mesothelioma - Sex: Both - Age: All Ages (Number)
8000,Zimbabwe,ZWE,2010,929,53,130,805,139,83,113,...,89,88,360,960,9,49,37,644,37,16
8001,Zimbabwe,ZWE,2011,919,53,131,810,139,82,114,...,93,88,362,947,10,49,37,644,37,16
8002,Zimbabwe,ZWE,2012,916,54,133,825,140,82,116,...,96,89,371,945,10,50,38,655,37,16
8003,Zimbabwe,ZWE,2013,917,54,136,844,141,83,118,...,97,90,385,949,10,50,38,670,38,16
8004,Zimbabwe,ZWE,2014,931,56,140,872,144,85,121,...,99,93,405,966,10,51,39,693,38,16
8005,Zimbabwe,ZWE,2015,948,59,145,902,149,87,125,...,104,96,426,988,11,53,40,719,39,16
8006,Zimbabwe,ZWE,2016,966,61,150,932,153,89,129,...,109,100,449,1012,11,54,42,744,40,17
8007,Zimbabwe,ZWE,2017,982,63,154,960,156,91,133,...,112,102,471,1035,12,56,43,767,41,17
8008,Zimbabwe,ZWE,2018,998,66,159,993,160,92,137,...,115,105,495,1059,12,57,44,792,43,17
8009,Zimbabwe,ZWE,2019,1016,68,164,1026,165,95,141,...,118,108,517,1087,12,59,45,818,44,18

In [5]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
lung_cancer_examples = "Resources/lung_cancer_examples.csv"


# Read the  Data and  store into a Pandas DataFrame
lung_cancer_examples_df = pd.read_csv(lung_cancer_examples)

lung_cancer_examples_df.tail(10)

          Name    Surname  Age  Smokes  AreaQ  Alkhol  Result
49  Katharine     Hepburn   62      20      5       6       1
50  Katharine     Hepburn   42      12      6       2       0
51     Barbra   Streisand   44      30      1       6       1
52     Maggie       Smith   26      34      1       8       1
53     Glenda     Jackson   35      20      5       1       0
54     Ernest    Borgnine   26      13      6       1       0
55       Alec    Guinness   77      20      5       4       1
56   Charlton      Heston   75      15      3       5       1
57    Gregory        Peck   43      30      3       8       1
58     Sidney     Poitier   51      25      9       0       0

In [6]:

# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
Lung_Bronchus_Cancer_NYC = "Resources/Lung and Bronchus Cancer_NYC.csv"

In [9]:
# Read the  Data and  store into a Pandas DataFrame
Lung_Bronchus_Cancer_NYC_df = pd.read_csv(Lung_Bronchus_Cancer_NYC, skiprows = 7)

Lung_Bronchus_Cancer_NYC_df

,2011-2015,Citywide,New York City,New York City,1,Lung and Bronchus Cancer,41.7,59.7,48.9,"2,109.40","2,178.80","4,288.20",Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,2011-2015,Borough,Bronx,Bronx,1,Lung and Bronchus Cancer,40.4,61.8,48.7,318.6,328.0,646.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011-2015,Borough,Brooklyn,Brooklyn,2,Lung and Bronchus Cancer,38.5,62.7,48.2,570.8,660.2,"1,231",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011-2015,Borough,Manhattan,Manhattan,3,Lung and Bronchus Cancer,47.4,53.7,49.7,498.4,408.0,906.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011-2015,Borough,Queens,Queens,4,Lung and Bronchus Cancer,38.0,56.2,45.5,550.0,602.6,"1,152.60",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011-2015,Borough,Staten Island,Staten Island,5,Lung and Bronchus Cancer,56.5,76.1,64.7,171.6,180.0,351.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Name:Lung and Bronchus Cancer,Measure:Age Adjusted Rate - Males (per 100000),How Calculated:<p>Average&nbsp;annual&nbsp;num...,Source(s):New York State Cancer Registry,Year:2011-2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NYC Department of Health and Mental Hygiene,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Environment & Health Data Portal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,More information can be found at: http://nyc.g...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Accessed 05/04/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
Provisional_Cancer_Death = "Resources/AH_Provisional_Cancer_Death_Counts_by_Month_and_Year__2020-2021.csv"


# Read the  Data and  store into a Pandas DataFrame
Provisional_Cancer_Death_df = pd.read_csv(Provisional_Cancer_Death)

Provisional_Cancer_Death_df.tail(10)

,Data As Of,Start Date,End Date,Country,Year,Month,Sex,Age Group,Race and Hispanic Origin,Malignant neoplasms (C00-C97),...,Malignant neoplasm of breast (C50),Malignant neoplasm of cervix uteri (C53),"Malignant neoplasms of corpus uteri and uterus, part unspecified (C54-C55)",Malignant neoplasm of ovary (C56),Malignant neoplasm of prostate (C61),Malignant neoplasms of kidney and renal pelvis (C64-C65),Malignant neoplasm of bladder (C67),"Malignant neoplasms of meninges, brain and other parts of central nervous system (C70-C72)","Malignant neoplasms of lymphoid, hematopoietic and related tissue (C81-C96)","All other and unspecified malignant neoplasms (C17,C23-C24,C26-C31,C37-C41,C44-C49,C51-C52,C57-C60,C62-C63,C66,C68-C69,C73-C80,C97)"
2806,11/23/2021,01/01/2021,01/31/2021,United States,2021,1,Male (M),75 years and over,Unknown,13,...,0,0,0,0,1,0,0,1,1,1
2807,11/23/2021,02/01/2021,02/28/2021,United States,2021,2,Male (M),75 years and over,Unknown,18,...,0,0,0,0,4,0,3,1,2,3
2808,11/23/2021,03/01/2021,03/31/2021,United States,2021,3,Male (M),75 years and over,Unknown,22,...,0,0,0,0,4,0,1,0,1,2
2809,11/23/2021,04/01/2021,04/30/2021,United States,2021,4,Male (M),75 years and over,Unknown,7,...,0,0,0,0,1,1,0,0,1,1
2810,11/23/2021,05/01/2021,05/31/2021,United States,2021,5,Male (M),75 years and over,Unknown,12,...,0,0,0,0,3,0,0,0,0,1
2811,11/23/2021,06/01/2021,06/30/2021,United States,2021,6,Male (M),75 years and over,Unknown,24,...,0,0,0,0,0,1,0,0,1,3
2812,11/23/2021,07/01/2021,07/31/2021,United States,2021,7,Male (M),75 years and over,Unknown,15,...,0,0,0,0,3,0,1,0,1,1
2813,11/23/2021,08/01/2021,08/31/2021,United States,2021,8,Male (M),75 years and over,Unknown,17,...,0,0,0,0,5,1,0,0,0,3
2814,11/23/2021,09/01/2021,09/30/2021,United States,2021,9,Male (M),75 years and over,Unknown,15,...,0,0,0,0,6,0,0,1,3,0
2815,11/23/2021,10/01/2021,10/31/2021,United States,2021,10,Male (M),75 years and over,Unknown,13,...,0,0,0,0,3,2,0,0,2,1

In [19]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
cancer_patients_data_sets = "Resources/cancer patient data sets.csv"


# Read the  Data and  store into a Pandas DataFrame
cancer_patients_data_sets_df = pd.read_csv(cancer_patients_data_sets)

cancer_patients_data_sets_df.tail(10)

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
990,P990,49,1,6,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High
991,P991,37,1,8,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,High
992,P992,26,2,7,7,7,7,7,6,7,...,2,7,6,7,6,7,2,3,1,High
993,P993,37,2,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,High
994,P994,33,1,6,7,7,7,7,7,6,...,8,5,7,6,7,8,7,6,2,High
995,P995,44,1,6,7,7,7,7,6,7,...,5,3,2,7,8,2,4,5,3,High
996,P996,37,2,6,8,7,7,7,6,7,...,9,6,5,7,2,4,3,1,4,High
997,P997,25,2,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High
998,P998,18,2,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,High
999,P999,47,1,6,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High

In [38]:

# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
Cancer_Atlas = "Resources/Cancer-Atlas-3rd-ed_Map-data.csv"


# Read the  Data and  store into a Pandas DataFrame
Cancer_Atlas_df = pd.read_csv(Cancer_Atlas, engine='python')
Cancer_Atlas_df.tail(10)

,Country or Territory,ISO 3 code,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Melanoma skin cancer incidence\nAge-standardized rate (world) per 100,000, both sexes, 2018",Breastfeeding at 12 months\nPercent (%) of children who receive any breast milk at 12 months of age,...,"Cervical cancer screening, HPV DNA testing\n2017","Radiotherapy availability\nNumber of radiotherapy machines per 1,000 cancer patients",Untreated deaths in pain\n2016,"Population-based cancer registries\nAvailability of population-based cancer registry (PBCR) data, 2019","Mortality registration quality\nQuality of mortality registration worldwide, 2007�2016",Cost of smoking-attributable diseases (US$ billions)\nEconomic cost of smoking-attributable diseases annually (healthcare spending and productivity losses)*,"Cervical cancer incidence rates\nAge-standardized rate (world) per 100,000, 2018","HIV prevalence (%)\nBoth sexes, 2017",UICC organizations\nA global network of cancer organizations,Global Relay For Life\n2017
204,Greenland,GRL,No data,No data,No data,No data,No data,No data,No data,No data,...,None,No data,No data,No information,No coverage,Data not featured,No data,No data,0.0,Non-participant
205,Holy See,VAT,No data,No data,No data,No data,No data,No data,No data,No data,...,None,No data,No data,No information,No coverage,Data not featured,No data,No data,0.0,Non-participant
206,R�union,REU,No data,No data,No data,12.4,No data,No data,3.3,No data,...,None,No data,No data,High quality PBCR,No coverage,Data not featured,10.5,No data,0.0,Non-participant
207,French Polynesia,PYF,No data,No data,No data,6.6,No data,No data,6.5,No data,...,None,No data,No data,PBCR,No coverage,Data not featured,10.1,No data,0.0,Non-participant
208,Guadeloupe,GLP,No data,No data,No data,10.2,No data,No data,1.5,No data,...,None,0.88,No data,PBCR,No coverage,Data not featured,9.3,No data,1.0,Non-participant
209,Guam,GUM,No data,No data,No data,8.5,No data,No data,No data,No data,...,None,2.58,No data,PBCR,No coverage,Data not featured,18.7,No data,0.0,Non-participant
210,Martinique,MTQ,No data,No data,No data,6.6,No data,No data,2,No data,...,None,1.46,No data,High quality PBCR,No coverage,Data not featured,7.6,No data,1.0,Non-participant
211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:

# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
ACPs_Breast_cancer = "Resources/ACPs_Breast_cancer.csv"


# Read the  Data and  store into a Pandas DataFrame
ACPs_Breast_cancer_df = pd.read_csv(ACPs_Breast_cancer)

ACPs_Breast_cancer_df.tail(10)

      ID                 sequence               class
939  940             YFSKGIPNVLRR  inactive - virtual
940  941          YGSIGLTNFGYLDKE  inactive - virtual
941  942         YKEPLKAVVKKLLEKE  inactive - virtual
942  943              YKKFRQLIQVN  inactive - virtual
943  944      YLADLFLAPQIHGAINRFQ  inactive - virtual
944  945  YLDKEVKLIKKMGNHLTNLRRVA  inactive - virtual
945  946  YLSESVETIKKLGDHITSLKKLW  inactive - virtual
946  947          YPIVDAAMRQLTETG  inactive - virtual
947  948         YQNIVKAVQYAARKLQ  inactive - virtual
948  949            YQQQKKYLGRMTE  inactive - virtual

In [25]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
ACPs_lung_cancer = "Resources/ACPs_lung_cancer.csv"


# Read the  Data and  store into a Pandas DataFrame
ACPs_lung_cancer_df = pd.read_csv(ACPs_lung_cancer)

ACPs_lung_cancer_df.tail(10)

      ID                 sequence               class
891  892             YFSKGIPNVLRR  inactive - virtual
892  893          YGSIGLTNFGYLDKE  inactive - virtual
893  894         YKEPLKAVVKKLLEKE  inactive - virtual
894  895              YKKFRQLIQVN  inactive - virtual
895  896      YLADLFLAPQIHGAINRFQ  inactive - virtual
896  897  YLDKEVKLIKKMGNHLTNLRRVA  inactive - virtual
897  898  YLSESVETIKKLGDHITSLKKLW  inactive - virtual
898  899          YPIVDAAMRQLTETG  inactive - virtual
899  900         YQNIVKAVQYAARKLQ  inactive - virtual
900  901            YQQQKKYLGRMTE  inactive - virtual