In [1]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to change the path if needed.)
lung_cancer = "Resources/survey_lung_cancer_rawdata.csv"


# Read the  Data and  store into a Pandas DataFrame
lung_cancer_df = pd.read_csv(lung_cancer)

In [17]:
lung_cancer_df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,NO,YES,YES,NO,NO,YES,NO,YES,YES,YES,YES,YES,YES,YES
1,M,74,YES,NO,NO,NO,YES,YES,YES,NO,NO,NO,YES,YES,YES,YES
2,F,59,NO,NO,NO,YES,NO,YES,NO,YES,NO,YES,YES,NO,YES,NO
3,M,63,YES,YES,YES,NO,NO,NO,NO,NO,YES,NO,NO,YES,YES,NO
4,F,63,NO,YES,NO,NO,NO,NO,NO,YES,NO,YES,YES,NO,NO,NO

In [20]:
# Extract specific columns
sample_df = pd.DataFrame(lung_cancer_df)
cols = [0, 1, 2, 10, 15]

#Show new dataframe with specific columns
sample_df = sample_df[sample_df.columns[cols]]
sample_df

    GENDER  AGE SMOKING ALCOHOL CONSUMING LUNG_CANCER
0        M   69      NO               YES         YES
1        M   74     YES                NO         YES
2        F   59      NO                NO          NO
3        M   63     YES               YES          NO
4        F   63      NO                NO          NO
..     ...  ...     ...               ...         ...
304      F   56      NO               YES         YES
305      M   70     YES               YES         YES
306      M   58     YES               YES         YES
307      M   67     YES               YES         YES
308      M   62      NO               YES         YES

[309 rows x 5 columns]

In [21]:
sample_df.to_csv('sample.csv', header = True, index = False)